apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f lgpd-odb-grafana-latest.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: pontus-comply-keycloak
  name: pontus-comply-keycloak
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 8080
  selector:
    io.kompose.service: pontus-comply-keycloak
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: pontus-comply-keycloak
status:
  loadBalancer: {}
